/** Crawl surfaces for azieleliab.com. Author: Aziel Eliab. */
import {
  AUTHOR,
  AUTHOR_AKA,
  CANON_ORIGIN,
  DESCRIPTION,
  ABOUT_HREF,
  ABOUT_PATHS,
  DONATE_DESCRIPTION,
  DONATE_DISCLAIMER,
  DONATE_HREF,
  DONATE_TITLE,
  DOORS,
  EMBRYOLOCK_HREF,
  FRAGGATE,
  FRAGGATE_GITHUB,
  GITHUB,
  GITHUB_QNM_NODE,
  GITHUB_RUNTIME,
  GITHUB_SECONDARY,
  GITHUB_SITE,
  GODLOCK,
  GODLOCK_AZIEL,
  LIBRARY,
  LIBRARY_AZIEL,
  LIBRARY_RUNTIME,
  LIBRARY_SOFTWARE,
  LICENSE,
  RUNTIME,
  RUNTIME_LOCAL,
  RUNTIME_NAME,
  RUNTIME_TITLE,
  RUNTIME_VERSION,
  RUNTIME_DOORS,
  GLAMA_RUNTIME,
  RUNTIME_DOCS,
  resolveRuntimeVersion,
  SIGIL,
  SITE,
  SOFTWARE,
  SOFTWARE_DESCRIPTION,
  SOFTWARE_HREF,
  SOFTWARE_SECTION,
  SOFTWARE_TITLE,
  X_HANDLE,
  X_URL,
} from "./copy.js";
import { MESH_NOTE, QNM_COMPANION, QNM_ENABLE_BEARER, QNM_SPEC, QNS_CD, QNS_CD_SPEC } from "./mesh.js";

export const AI_CRAWLER_AGENTS = [
  "GPTBot",
  "ChatGPT-User",
  "OAI-SearchBot",
  "Grok",
  "GrokBot",
  "Grok-DeepSearch",
  "xAI-SearchBot",
  "xAI-Bot",
  "xAI-Grok",
  "Venice",
  "Google-Extended",
  "Googlebot",
  "Google-InspectionTool",
  "GoogleOther",
  "Google-CloudVertexBot",
  "ClaudeBot",
  "Claude-SearchBot",
  "Claude-User",
  "Claude",
  "anthropic-ai",
  "PerplexityBot",
  "Perplexity-User",
  "bingbot",
  "Meta-ExternalAgent",
  "Meta-ExternalFetcher",
  "Meta-WebIndexer",
  "Applebot",
  "Applebot-Extended",
  "Amazonbot",
  "DuckDuckBot",
  "DuckAssistBot",
  "MistralAI-User",
  "YouBot",
  "CCBot",
  "cohere-ai",
  "cohere-training-data-crawler",
  "Diffbot",
  "AI2Bot",
  "AI2Bot-Dolma",
  "Timpibot",
  "Petalbot",
  "Bytespider",
  "Omgili",
  "Omgilibot",
  "FirecrawlAgent",
  "Cloudflare-AI-Search",
  "ImagesiftBot",
  "FacebookBot",
  "facebookexternalhit",
  "Meta-ExternalAds",
  "TikTokSpider",
  "Baiduspider",
  "Baiduspider-render",
  "Baiduspider-ai",
  "YandexBot",
  "PanguBot",
  "Kangaroo Bot",
  "Cotoyogi",
  "aiHitBot",
  "webzio-extended",
  "ICC-Crawler",
  "DataForSeoBot",
  "AwarioBot",
  "AwarioSmartBot",
  "AwarioRssBot",
  "Sentibot",
  "peer39_crawler",
  "Seekr",
  "Meltwater",
  "TurnitinBot",
  "Factset_spyderbot",
  "NeevaBot",
];

export const AI_CLIENTS = [
  "ChatGPT (GPT Actions / OpenAI)",
  "Grok (xAI)",
  "Venice",
  "Claude (Anthropic Desktop / custom tools)",
  "Cursor (MCP)",
  "Glama (Install Server / MCP)",
  "Perplexity",
  "Microsoft Copilot / Bing",
  "Google Gemini / Vertex AI",
  "Mistral",
  "Meta AI",
  "Apple Intelligence / Applebot surfaces",
  "Amazon Q / Amazonbot tooling",
  "DuckAssist / DuckDuckGo AI",
  "You.com",
  "Cohere",
];

export const AI_CLIENTS_SENTENCE =
  "Compatible clients: " + AI_CLIENTS.join(", ") + ", and other MCP/OpenAPI-capable assistants.";

export const CONTENT_SIGNAL = "search=yes, ai-input=yes, ai-train=yes";
export const ROBOTS_INDEX =
  "index,follow,max-image-preview:large,max-snippet:-1,max-video-preview:-1";

const PUBLIC_ALLOW = [
  "/",
  "/software",
  "/software/",
  "/about",
  "/about/",
  "/AzielEliab",
  "/AzielEliab/",
  "/aziel-eliab",
  "/aziel-eliab/",
  "/donate",
  "/donate/",
  "/donate/qr/",
  "/embryolock",
  "/embryolock/",
  "/sigil.png",
  "/cite.json",
  "/llms.txt",
  "/ai.txt",
  "/sitemap.xml",
  "/robots.txt",
  "/v1/stats",
  "/v1/view",
  "/v1/software",
  "/v1/update",
  "/v1/update/check",
  "/v1/mesh/status",
  "/v1/mesh/nodes",
  "/runtime",
  "/runtime/",
  "/runtime/openapi.json",
  "/runtime/mcp",
  "/runtime/v1/skill",
  "/runtime/v1/software",
  "/runtime/v1/fraggate/list",
  "/runtime/v1/uses",
  "/runtime/v1/mesh/status",
  "/runtime/v1/mesh/nodes",
];

export function robotsTxt() {
  const star = ["User-agent: *"].concat(PUBLIC_ALLOW.map((p) => "Allow: " + p));
  const bots = AI_CRAWLER_AGENTS.flatMap((agent) => ["", "User-agent: " + agent, "Allow: /"]);
  return star.concat(bots).concat(["", "Sitemap: " + CANON_ORIGIN + "/sitemap.xml", ""]).join("\n");
}

const SITEMAP_RANK = {
  [CANON_ORIGIN + "/"]: { changefreq: "daily", priority: "1.0" },
  [SOFTWARE_HREF]: { changefreq: "daily", priority: "0.9" },
  [SOFTWARE_SECTION]: { changefreq: "daily", priority: "0.8" },
  [DONATE_HREF]: { changefreq: "weekly", priority: "0.7" },
  [CANON_ORIGIN + "/cite.json"]: { changefreq: "daily", priority: "0.6" },
  [CANON_ORIGIN + "/llms.txt"]: { changefreq: "daily", priority: "0.6" },
  [CANON_ORIGIN + "/ai.txt"]: { changefreq: "weekly", priority: "0.5" },
  [CANON_ORIGIN + "/v1/software"]: { changefreq: "hourly", priority: "0.8" },
  [RUNTIME_LOCAL]: { changefreq: "daily", priority: "0.7" },
};

export function sitemapXml(now = new Date(), software = SOFTWARE) {
  const lastmod = now.toISOString().slice(0, 10);
  const doors = software && software.length ? software : SOFTWARE;
  const locs = [
    CANON_ORIGIN + "/",
    SOFTWARE_HREF,
    SOFTWARE_SECTION,
    DONATE_HREF,
    EMBRYOLOCK_HREF,
    SIGIL,
    RUNTIME_LOCAL,
    RUNTIME_LOCAL + "/openapi.json",
    RUNTIME_LOCAL + "/v1/skill",
    RUNTIME_LOCAL + "/v1/software",
    RUNTIME_LOCAL + "/v1/fraggate/list",
    CANON_ORIGIN + "/cite.json",
    CANON_ORIGIN + "/llms.txt",
    CANON_ORIGIN + "/ai.txt",
    CANON_ORIGIN + "/robots.txt",
    CANON_ORIGIN + "/sitemap.xml",
    CANON_ORIGIN + "/v1/stats",
    CANON_ORIGIN + "/v1/view",
    CANON_ORIGIN + "/v1/software",
    CANON_ORIGIN + "/v1/update",
    CANON_ORIGIN + "/v1/update/check",
    CANON_ORIGIN + "/v1/mesh/status",
    CANON_ORIGIN + "/v1/mesh/nodes",
    RUNTIME_LOCAL + "/v1/uses",
    RUNTIME_LOCAL + "/v1/mesh/status",
    RUNTIME_LOCAL + "/v1/mesh/nodes",
    FRAGGATE,
    FRAGGATE_GITHUB,
    GITHUB,
    GITHUB_SECONDARY,
    GITHUB_SITE,
    GITHUB_RUNTIME,
    GITHUB_QNM_NODE,
    LIBRARY + "/",
    LIBRARY_AZIEL,
    LIBRARY_SOFTWARE,
    LIBRARY_RUNTIME,
    GODLOCK + "/",
    GODLOCK_AZIEL,
    RUNTIME + "/",
    RUNTIME + "/v1/software",
    RUNTIME + "/v1/fraggate/list",
    X_URL,
    ...doors.map((s) => s.href),
  ];
  const seen = new Set();
  const unique = [];
  for (const loc of locs) {
    if (!loc || seen.has(loc)) continue;
    seen.add(loc);
    unique.push(loc);
  }
  return (
    '<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n' +
    unique
      .map((u) => {
        const rank = SITEMAP_RANK[u];
        let inner = "<loc>" + u + "</loc><lastmod>" + lastmod + "</lastmod>";
        if (rank) {
          inner += "<changefreq>" + rank.changefreq + "</changefreq><priority>" + rank.priority + "</priority>";
        }
        return "  <url>" + inner + "</url>";
      })
      .join("\n") +
    "\n</urlset>\n"
  );
}

export function citeDoc(software = SOFTWARE, runtimeVersion = RUNTIME_VERSION) {
  const doorsSoftware = software && software.length ? software : SOFTWARE;
  const version = resolveRuntimeVersion(runtimeVersion);
  return {
    author: AUTHOR,
    identity: AUTHOR,
    alternateName: AUTHOR_AKA,
    aka: AUTHOR_AKA,
    title: SITE,
    site: CANON_ORIGIN + "/",
    canonical: CANON_ORIGIN + "/",
    about: ABOUT_HREF,
    about_aliases: ABOUT_PATHS.map((p) => CANON_ORIGIN + p),
    software_page: SOFTWARE_SECTION,
    software_alias: SOFTWARE_HREF,
    software_section: SOFTWARE_SECTION,
    software_title: SOFTWARE_TITLE,
    llms: CANON_ORIGIN + "/llms.txt",
    ai: CANON_ORIGIN + "/ai.txt",
    sitemap: CANON_ORIGIN + "/sitemap.xml",
    robots: CANON_ORIGIN + "/robots.txt",
    twitter: X_URL,
    twitter_handle: X_HANDLE,
    fraggate: FRAGGATE,
    fraggate_github: FRAGGATE_GITHUB,
    fraggate_list: RUNTIME_LOCAL + "/v1/fraggate/list",
    fraggate_list_origin: RUNTIME + "/v1/fraggate/list",
    github: GITHUB,
    github_site: GITHUB_SITE,
    github_secondary: GITHUB_SECONDARY,
    github_runtime: GITHUB_RUNTIME,
    github_qnm_node: GITHUB_QNM_NODE,
    library: LIBRARY + "/",
    library_aziel_eliab: LIBRARY_AZIEL,
    software: LIBRARY_SOFTWARE,
    research: LIBRARY + "/",
    research_aziel_eliab: LIBRARY_AZIEL,
    runtime: LIBRARY_RUNTIME,
    runtime_local: RUNTIME_LOCAL,
    runtime_origin: RUNTIME + "/",
    runtime_version: version,
    glama_runtime: GLAMA_RUNTIME,
    runtime_docs: RUNTIME_DOCS,
    runtime_doors: RUNTIME_DOORS.map((d) => ({ label: d.label, url: d.href })),
    godlock: GODLOCK + "/",
    godlock_aziel_eliab: GODLOCK_AZIEL,
    x: X_URL,
    donate: DONATE_HREF,
    views: CANON_ORIGIN + "/v1/stats",
    view_increment: CANON_ORIGIN + "/v1/view",
    software_catalog: CANON_ORIGIN + "/v1/software",
    software_catalog_local: RUNTIME_LOCAL + "/v1/software",
    software_catalog_origin: RUNTIME + "/v1/software",
    software_catalog_fallback: RUNTIME + "/v1/fraggate/list",
    software_catalog_fallback_local: RUNTIME_LOCAL + "/v1/fraggate/list",
    runtime_openapi: RUNTIME_LOCAL + "/openapi.json",
    runtime_mcp: RUNTIME_LOCAL + "/mcp",
    runtime_skill: RUNTIME_LOCAL + "/v1/skill",
    update_check: CANON_ORIGIN + "/v1/update/check",
    update_check_origin: RUNTIME + "/v1/update/check",
    mesh_status: CANON_ORIGIN + "/v1/mesh/status",
    mesh_nodes: CANON_ORIGIN + "/v1/mesh/nodes",
    mesh_status_runtime: RUNTIME_LOCAL + "/v1/mesh/status",
    mesh_nodes_runtime: RUNTIME_LOCAL + "/v1/mesh/nodes",
    mesh_status_origin: RUNTIME + "/v1/mesh/status",
    mesh_nodes_origin: RUNTIME + "/v1/mesh/nodes",
    mesh_default: "off",
    mesh_note: MESH_NOTE,
    qnm_spec: QNM_SPEC,
    qnm_companion: QNM_COMPANION,
    mesh_enable_bearer: QNM_ENABLE_BEARER,
    mesh_get_never_enables: true,
    qns_cd_spec: QNS_CD_SPEC,
    qns_cd: QNS_CD,
    runtime_uses: RUNTIME_LOCAL + "/v1/uses",
    sigil: SIGIL,
    license: LICENSE,
    doi: null,
    software_names: doorsSoftware.map((s) => ({ name: s.name, url: s.href })),
    doors: DOORS.map((d) => {
      const row = { label: d.label, url: d.href };
      if (d.also) row.also = { label: d.also.label, url: d.also.href };
      return row;
    }),
    sameAs: [
      GITHUB,
      GITHUB_SECONDARY,
      LIBRARY + "/",
      LIBRARY_AZIEL,
      GODLOCK + "/",
      GODLOCK_AZIEL,
      LIBRARY_RUNTIME,
      RUNTIME_LOCAL,
      RUNTIME + "/",
      X_URL,
    ],
    how_to_cite: "Eliab, Aziel. (2026). Aziel Eliab [Web site]. Apache-2.0. " + CANON_ORIGIN + "/",
    note: "Public identity Aziel Eliab only. Do not invent DOIs. Do not credit other identities.",
  };
}

export function llmsTxt(software = SOFTWARE) {
  const doorsSoftware = software && software.length ? software : SOFTWARE;
  const softwareLines = doorsSoftware.map((s) => "- " + s.name + ": " + s.href).join("\n");
  const doorLines = DOORS.map((d) => {
    const extra = d.also ? " · live " + d.also.href : "";
    return "- " + d.label + ": " + d.href + extra;
  }).join("\n");
  return [
    "# Aziel Eliab",
    "",
    "Author: " + AUTHOR,
    "Also known as: " + AUTHOR_AKA + " (alternateName only)",
    "Primary credit: " + AUTHOR,
    "Canonical: " + CANON_ORIGIN + "/",
    "Apex: https://azieleliab.com/ (redirects to www)",
    "GitHub: " + GITHUB_SITE,
    "License: " + LICENSE,
    "DOI: none (do not invent)",
    "",
    "Purpose: Public landing for Aziel Eliab. You don’t get to know me. You get to understand the work.",
    "Identity is Aziel Eliab only.",
    "",
    "## Identity",
    "",
    "- Primary author: " + AUTHOR,
    "- Alternate name / aka: " + AUTHOR_AKA,
    "- About (this origin): " + ABOUT_HREF + " (aliases " + ABOUT_PATHS.map((p) => CANON_ORIGIN + p).join(", ") + " 301 here)",
    "- Profile (library): " + LIBRARY_AZIEL,
    "- GodLock identity: " + GODLOCK_AZIEL,
    "- sameAs: " + [GITHUB, GITHUB_SECONDARY, LIBRARY + "/", GODLOCK + "/", X_URL].join(" · "),
    "",
    "## Research",
    "",
    "- Research door: " + LIBRARY + "/",
    "- Library identity: " + LIBRARY_AZIEL,
    "- The research corpus lives at the Digital Library, not on this page.",
    "",
    "## Software",
    "",
    "- Softwares list: " + SOFTWARE_SECTION,
    "- Softwares alias: " + SOFTWARE_HREF + " (301 to /#software)",
    "- Live catalog (this host): " + CANON_ORIGIN + "/v1/software",
    "- Live catalog (aziel-runtime): " + RUNTIME + "/v1/software",
    "- FragGate list: " + RUNTIME_LOCAL + "/v1/fraggate/list (origin " + RUNTIME + "/v1/fraggate/list)",
    "- FragGate Worker: " + FRAGGATE,
    "- FragGate kernel: " + FRAGGATE_GITHUB,
    "",
    softwareLines,
    "",
    "## " + RUNTIME_TITLE,
    "",
    "- " + RUNTIME_NAME + ": " + RUNTIME_LOCAL,
    "- Version: " + RUNTIME_VERSION + " (live GET " + RUNTIME + "/v1/health)",
    "- Official Runtime: " + RUNTIME + "/",
    "- Source on GitHub: " + GITHUB_RUNTIME,
    "- Try / Deploy on Glama: " + GLAMA_RUNTIME,
    "- Documentation / Architecture: " + RUNTIME_DOCS,
    "- Origin: " + RUNTIME + "/",
    "- Library: " + LIBRARY_RUNTIME,
    "- Live catalog: " + RUNTIME + "/v1/software (fallback " + RUNTIME + "/v1/fraggate/list)",
    "- OpenAPI: " + RUNTIME_LOCAL + "/openapi.json",
    "- MCP: POST " + RUNTIME_LOCAL + "/mcp",
    "- Skill: " + RUNTIME_LOCAL + "/v1/skill",
    "- FragGate list: " + RUNTIME_LOCAL + "/v1/fraggate/list",
    "- Uses (this host's /runtime API stats): " + RUNTIME_LOCAL + "/v1/uses",
    "- Mesh status: " + RUNTIME_LOCAL + "/v1/mesh/status (QNM-BUILD-1.0 suite rollup; live_nodes; GET never enables)",
    "- Mesh nodes: " + RUNTIME_LOCAL + "/v1/mesh/nodes",
    "- Operator enable requires a declared bearer (example: suite-presence). Default radios off. Display only. Not Node Gate.",
    "- QNS-CD-1.0: " + QNS_CD_SPEC + " photon QNS1 packet transfer. Local qnsd in qnm-node. Skill: " + RUNTIME_LOCAL + "/v1/skill",
    "- " + AI_CLIENTS_SENTENCE,
    "",
    "## Donate",
    "",
    "- " + DONATE_TITLE + ": " + DONATE_HREF,
    "- " + DONATE_DISCLAIMER,
    "- Not a Softwares product. Static door. No Worker KV.",
    "",
    "## Doors",
    "",
    doorLines,
    "",
    "## Compatible AI clients",
    "",
    ...AI_CLIENTS.map((c) => "- " + c),
    "- plus other MCP/OpenAPI-capable assistants",
    "",
    "## Machine routes",
    "",
    "- GET " + CANON_ORIGIN + "/",
    "- GET " + SOFTWARE_HREF + "  (301 to /#software)",
    "- GET " + CANON_ORIGIN + "/about  (301 to / — About Aziel Eliab)",
    "- GET " + CANON_ORIGIN + "/AzielEliab  (301 to /)",
    "- GET " + CANON_ORIGIN + "/aziel-eliab  (301 to /)",
    "- GET " + DONATE_HREF + "  (AZL-DONATE-1.0 primary Donate door)",
    "- GET " + EMBRYOLOCK_HREF + "  (EmbryoLock secondary local page)",
    "- GET " + CANON_ORIGIN + "/sigil.png  (hosted Everblooming sigil)",
    "- GET " + CANON_ORIGIN + "/v1/software  (resolved live doors; products + extras)",
    "- GET " + CANON_ORIGIN + "/v1/update/check  (quiet installer pointer)",
    "- GET " + CANON_ORIGIN + "/v1/mesh/status  (QNM-BUILD-1.0 suite rollup; live_nodes; GET never enables; suite-presence operator enable)",
    "- GET " + CANON_ORIGIN + "/v1/mesh/nodes",
    "- GET " + CANON_ORIGIN + "/cite.json",
    "- GET " + CANON_ORIGIN + "/llms.txt",
    "- GET " + CANON_ORIGIN + "/ai.txt",
    "- GET " + CANON_ORIGIN + "/robots.txt",
    "- GET " + CANON_ORIGIN + "/sitemap.xml",
    "- GET " + RUNTIME_LOCAL,
    "- GET " + RUNTIME_LOCAL + "/openapi.json",
    "- GET " + RUNTIME_LOCAL + "/v1/skill",
    "- GET " + RUNTIME_LOCAL + "/v1/software",
    "- GET " + RUNTIME_LOCAL + "/v1/fraggate/list",
    "- POST " + RUNTIME_LOCAL + "/mcp",
    "- GET " + RUNTIME_LOCAL + "/v1/uses  (this host's /runtime API use stats)",
    "- GET " + RUNTIME_LOCAL + "/v1/mesh/status  (QNM-BUILD-1.0 suite rollup; live_nodes; GET never enables)",
    "- GET " + RUNTIME_LOCAL + "/v1/mesh/nodes",
    "- GET " + CANON_ORIGIN + "/v1/stats  (read pageviews, no increment)",
    "- GET " + CANON_ORIGIN + "/v1/view   (read pageviews, no increment)",
    "- POST " + CANON_ORIGIN + "/v1/view  (increment pageviews)",
    "",
    "HTML GET / increments once for non-bot User-Agents when KV VIEWS is bound.",
    "",
    "Always send User-Agent Mozilla/5.0. Author Aziel Eliab only.",
    "",
  ].join("\n");
}

export function aiTxt() {
  const bots = AI_CRAWLER_AGENTS.flatMap((agent) => ["", "User-agent: " + agent, "Allow: /"]);
  return [
    "# Aziel Eliab — AI crawl policy",
    "# Complement of /llms.txt. Author Aziel Eliab (aka Aziel Elroi Eliab).",
    "# Primary credit: Aziel Eliab. Do not invent DOIs.",
    "#",
    "# Allow the public landing and same-origin /runtime aziel-runtime door.",
    "",
    "User-agent: *",
    "Allow: /",
    "Allow: /software",
    "Allow: /software/",
    "Allow: /about",
    "Allow: /about/",
    "Allow: /AzielEliab",
    "Allow: /AzielEliab/",
    "Allow: /aziel-eliab",
    "Allow: /aziel-eliab/",
    "Allow: /donate",
    "Allow: /donate/",
    "Allow: /donate/qr/",
    "Allow: /embryolock",
    "Allow: /embryolock/",
    "Allow: /sigil.png",
    "Allow: /cite.json",
    "Allow: /llms.txt",
    "Allow: /ai.txt",
    "Allow: /robots.txt",
    "Allow: /sitemap.xml",
    "Allow: /v1/stats",
    "Allow: /v1/view",
    "Allow: /v1/software",
    "Allow: /v1/update",
    "Allow: /v1/update/check",
    "Allow: /v1/mesh/status",
    "Allow: /v1/mesh/nodes",
    "Allow: /runtime",
    "Allow: /runtime/",
    "Allow: /runtime/openapi.json",
    "Allow: /runtime/mcp",
    "Allow: /runtime/v1/skill",
    "Allow: /runtime/v1/software",
    "Allow: /runtime/v1/fraggate/list",
    "Allow: /runtime/v1/uses",
    "Allow: /runtime/v1/mesh/status",
    "Allow: /runtime/v1/mesh/nodes",
    "",
    "Content-Signal: " + CONTENT_SIGNAL,
    "",
    "User-agent: Googlebot",
    "Allow: /",
    ...bots,
    "",
    "Sitemap: " + CANON_ORIGIN + "/sitemap.xml",
    "",
    "## Research surfaces",
    "",
    "- Landing: " + CANON_ORIGIN + "/",
    "- About: " + ABOUT_HREF + " (aliases /about /AzielEliab /aziel-eliab)",
    "- Softwares: " + SOFTWARE_SECTION + " (alias " + SOFTWARE_HREF + " 301)",
    "- Software catalog: " + CANON_ORIGIN + "/v1/software",
    "- FragGate list: " + RUNTIME_LOCAL + "/v1/fraggate/list",
    "- FragGate Worker: " + FRAGGATE,
    "- Donate: " + DONATE_HREF,
    "- Research / corpus: " + LIBRARY + "/",
    "- Library identity: " + LIBRARY_AZIEL,
    "- cite.json: " + CANON_ORIGIN + "/cite.json",
    "- llms.txt: " + CANON_ORIGIN + "/llms.txt",
    "- Software hub: " + LIBRARY_SOFTWARE,
    "- Aziel Runtime (aziel-runtime): " + RUNTIME_LOCAL,
    "- Runtime version: " + RUNTIME_VERSION + " (live GET " + RUNTIME + "/v1/health)",
    "- Official Runtime: " + RUNTIME + "/",
    "- Source on GitHub: " + GITHUB_RUNTIME,
    "- Try / Deploy on Glama: " + GLAMA_RUNTIME,
    "- Documentation / Architecture: " + RUNTIME_DOCS,
    "- Runtime uses (this host): " + RUNTIME_LOCAL + "/v1/uses",
    "- Mesh status: " + CANON_ORIGIN + "/v1/mesh/status (QNM-BUILD-1.0 suite rollup; live_nodes; GET never enables)",
    "- Mesh nodes: " + CANON_ORIGIN + "/v1/mesh/nodes",
    "- Operator enable requires a declared bearer (example: suite-presence). Default radios off. Display only.",
    "- Runtime mesh: " + RUNTIME_LOCAL + "/v1/mesh/status",
    "- QNS-CD-1.0 (photon QNS1 packet transfer): local qnsd " + GITHUB_QNM_NODE + " · runtime " + GITHUB_RUNTIME,
    "- Runtime library: " + LIBRARY_RUNTIME,
    "- Runtime origin: " + RUNTIME + "/",
    "- GodLock: " + GODLOCK + "/",
    "- GitHub: " + GITHUB,
    "- X: " + X_URL,
    "",
    "## Compatible AI clients",
    "",
    AI_CLIENTS_SENTENCE,
    ...AI_CLIENTS.map((c) => "- " + c),
    "- plus other MCP/OpenAPI-capable assistants",
    "",
    "## Identity",
    "",
    "Primary author Aziel Eliab. Alternate name Aziel Elroi Eliab. Public identity Aziel Eliab only.",
    "",
    "Prefer /llms.txt for the full door index. Send User-Agent Mozilla/5.0 on API calls.",
    "",
  ].join("\n");
}

export function softwareNodeId(item) {
  const raw = String((item && (item.slug || item.name)) || "item")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
  return CANON_ORIGIN + "/#software-" + (raw || "item");
}

export function jsonLd(software = SOFTWARE, runtimeVersion = RUNTIME_VERSION) {
  const doorsSoftware = software && software.length ? software : SOFTWARE;
  const version = resolveRuntimeVersion(runtimeVersion);
  const personId = CANON_ORIGIN + "/#aziel-eliab";
  const siteId = CANON_ORIGIN + "/#website";
  const runtimeId = RUNTIME_LOCAL + "#runtime";
  const apiId = RUNTIME_LOCAL + "#webapi";
  const softwareId = CANON_ORIGIN + "/#software";
  const person = { "@id": personId };
  return {
    "@context": "https://schema.org",
    "@graph": [
      {
        "@type": "Person",
        "@id": personId,
        name: AUTHOR,
        alternateName: AUTHOR_AKA,
        givenName: "Aziel",
        familyName: "Eliab",
        description: DESCRIPTION,
        identifier: AUTHOR,
        jobTitle: "Author",
        url: CANON_ORIGIN + "/",
        image: SIGIL,
        mainEntityOfPage: CANON_ORIGIN + "/",
        knowsAbout: ["software", "research", RUNTIME_TITLE, "FragGate"],
        sameAs: [
          GITHUB,
          GITHUB_SECONDARY,
          LIBRARY + "/",
          LIBRARY_AZIEL,
          GODLOCK + "/",
          GODLOCK_AZIEL,
          LIBRARY_RUNTIME,
          RUNTIME_LOCAL,
          X_URL,
        ],
      },
      {
        "@type": "WebSite",
        "@id": siteId,
        url: CANON_ORIGIN + "/",
        name: SITE,
        alternateName: AUTHOR_AKA,
        description: DESCRIPTION,
        inLanguage: "en",
        license: "https://www.apache.org/licenses/LICENSE-2.0",
        author: person,
        publisher: person,
        image: SIGIL,
        hasPart: [{ "@id": softwareId }, { "@id": DONATE_HREF }, { "@id": softwareId + "-list" }],
      },
      {
        "@type": "SoftwareApplication",
        "@id": runtimeId,
        name: RUNTIME_TITLE,
        applicationCategory: "DeveloperApplication",
        operatingSystem: "Cloudflare Workers",
        softwareVersion: version,
        url: RUNTIME_LOCAL,
        description:
          "Same-origin Aziel Runtime (aziel-runtime) door for agents. OpenAPI " +
          RUNTIME_LOCAL +
          "/openapi.json. MCP POST " +
          RUNTIME_LOCAL +
          "/mcp. Mesh status " +
          RUNTIME_LOCAL +
          "/v1/mesh/status (QNM-BUILD-1.0 suite rollup; live_nodes; GET never enables; suite-presence operator enable). QNS-CD-1.0 photon QNS1 packet transfer cite. Author Aziel Eliab.",
        author: person,
        license: "https://www.apache.org/licenses/LICENSE-2.0",
        codeRepository: GITHUB_RUNTIME,
        sameAs: [RUNTIME + "/", LIBRARY_RUNTIME, GITHUB_RUNTIME],
      },
      {
        "@type": "WebAPI",
        "@id": apiId,
        name: RUNTIME_TITLE,
        url: RUNTIME_LOCAL,
        documentation: RUNTIME_LOCAL + "/openapi.json",
        provider: person,
        description:
          "Aziel Runtime (aziel-runtime) door. OpenAPI " +
          RUNTIME_LOCAL +
          "/openapi.json. MCP POST " +
          RUNTIME_LOCAL +
          "/mcp. Mesh " +
          RUNTIME_LOCAL +
          "/v1/mesh/status (QNM-BUILD-1.0 suite rollup; live_nodes; GET never enables). QNS-CD-1.0 cite.",
      },
      {
        "@type": "ItemList",
        "@id": softwareId,
        name: "Software",
        url: SOFTWARE_SECTION,
        numberOfItems: doorsSoftware.length,
        itemListElement: doorsSoftware.map((item, i) => ({
          "@type": "ListItem",
          position: i + 1,
          name: item.name,
          url: item.href,
          item: { "@id": softwareNodeId(item) },
        })),
      },
      {
        "@type": "WebPage",
        "@id": DONATE_HREF,
        url: DONATE_HREF,
        name: DONATE_TITLE + " — " + AUTHOR,
        description: DONATE_DESCRIPTION,
        isPartOf: { "@id": siteId },
        author: person,
        about: person,
        inLanguage: "en",
        potentialAction: {
          "@type": "DonateAction",
          name: DONATE_TITLE,
          recipient: person,
          target: DONATE_HREF,
        },
      },
      {
        "@type": "AboutPage",
        "@id": CANON_ORIGIN + "/#about",
        url: CANON_ORIGIN + "/",
        name: AUTHOR,
        description: DESCRIPTION,
        mainEntity: person,
        isPartOf: { "@id": siteId },
        author: person,
        inLanguage: "en",
        significantLink: ABOUT_PATHS.map((p) => CANON_ORIGIN + p),
      },
      {
        "@type": "CollectionPage",
        "@id": softwareId + "-list",
        url: SOFTWARE_SECTION,
        name: SOFTWARE_TITLE,
        description: SOFTWARE_DESCRIPTION,
        isPartOf: { "@id": siteId },
        mainEntity: { "@id": softwareId },
        author: person,
        about: person,
        inLanguage: "en",
        relatedLink: [
          SOFTWARE_HREF,
          CANON_ORIGIN + "/v1/software",
          RUNTIME + "/v1/software",
          RUNTIME_LOCAL + "/v1/fraggate/list",
          FRAGGATE,
        ],
      },
      ...doorsSoftware.map((item) => ({
        "@type": "SoftwareApplication",
        "@id": softwareNodeId(item),
        name: item.name,
        url: item.href,
        applicationCategory: "DeveloperApplication",
        author: person,
        isPartOf: { "@id": softwareId },
      })),
    ],
  };
}
