/** Crawl surfaces for azieleliab.com. Author: Aziel Eliab. */
import {
  AUTHOR,
  AUTHOR_AKA,
  CANON_ORIGIN,
  DESCRIPTION,
  ABOUT_HREF,
  ABOUT_PATHS,
  DONATE_DESCRIPTION,
  DONATE_DISCLAIMER,
  DONATE_HREF,
  DONATE_TITLE,
  DOORS,
  EMBRYOLOCK_HREF,
  FRAGGATE,
  FRAGGATE_GITHUB,
  GITHUB,
  GITHUB_QNM_NODE,
  GITHUB_RUNTIME,
  GITHUB_SECONDARY,
  GITHUB_SITE,
  GODLOCK,
  GODLOCK_AZIEL,
  HEDIDNTJUMP,
  LIBRARY,
  LIBRARY_AZIEL,
  LIBRARY_RUNTIME,
  LIBRARY_SOFTWARE,
  LICENSE,
  RUNTIME,
  RUNTIME_LOCAL,
  RUNTIME_NAME,
  RUNTIME_TITLE,
  RUNTIME_VERSION,
  RUNTIME_DOORS,
  GLAMA_RUNTIME,
  PERSON_ID,
  PERSON_SAME_AS,
  RUNTIME_DOCS,
  RUNTIME_DOWNLOAD,
  RUNTIME_DOWNLOAD_NOTE,
  RUNTIME_DOWNLOAD_V1,
  RUNTIME_GIT_SHA,
  RUNTIME_GIT_SHORT,
  RUNTIME_BRANCH,
  RUNTIME_HUMAN_UI,
  RUNTIME_ID,
  RUNTIME_NAMED_TOOLS,
  RUNTIME_VERSION_ID,
  DUAL_SURFACE,
  FIELD_100,
  MASTER_33_MCP,
  SISTER_PRODUCTS_NOTE,
  TRADES_RUNTIME,
  TRADES_RUNTIME_CITE,
  TRADES_RUNTIME_DOWNLOAD,
  TRADES_RUNTIME_GITHUB,
  TRADES_RUNTIME_HEALTH,
  TRADES_RUNTIME_ID,
  TRADES_RUNTIME_LLMS,
  TRADES_RUNTIME_MCP,
  TRADES_RUNTIME_NAME,
  TRADES_RUNTIME_NOTE,
  TRADES_RUNTIME_ONE_LINE,
  TRADES_RUNTIME_OPENAPI,
  TRADES_RUNTIME_SAME_AS,
  TRADES_RUNTIME_SKILL,
  TRADES_RUNTIME_SLUG,
  TRADES_RUNTIME_STATS,
  TRADES_RUNTIME_VERSION,
  resolveRuntimeVersion,
  runtimeToolId,
  sisterProductsCite,
  spectrallockCite,
  SPECTRALLOCK_HANDWRITING,
  SPECTRALLOCK_OCR_NOTE,
  SPECTRALLOCK_ONE_LINE,
  SPECTRALLOCK_RECOVER,
  SPECTRALLOCK_SLUG,
  SPECTRALLOCK_UNREDACT,
  SPECTRALLOCK_WORKER,
  tradesRuntimeCite,
  WEBSITE_ID,
  BRANDMARK_NAME,
  SIGIL,
  SITE,
  SOFTWARE,
  SOFTWARE_DESCRIPTION,
  SOFTWARE_HREF,
  SOFTWARE_TITLE,
  AUTHOR_AKA_LIST,
  HASH_REDIRECTS,
  INDEXABLE_SECTIONS,
  RECEIPTS_HREF,
  WHO_HREF,
  X_HANDLE,
  X_URL,
} from "./copy.js";
import {
  ABOUT_ALIAS_HREFS,
  ABOUT_MACHINE_HREFS,
  ABOUT_PUBLISHED_LINES,
  DISAMBIGUATING_DESCRIPTION,
  HEBREW_NAME_DEFINITION,
  HEBREW_NAME_FORMS,
  LIBRARY_STATS,
  LIBRARY_STATS_FALLBACK,
  NAME_MISSPELLINGS,
  PERSON_JOB_TITLE,
  SITE_COVERAGE,
  SOFTWARE_DEVELOPER_ANSWER,
  STATS_COUNTERS,
  STATS_NOTE,
  VISIBLE_LOCK_LINE,
  WHAT_AZIEL_ELIAB_DOES,
  WHAT_HE_DOES_ANSWER,
  WHAT_HE_DOES_FAQ_NAMES,
  WHAT_HE_DOES_SOFTWARES,
  SOFTWARES_ADDENDUM,
  SPECTRALLOCK_FAQ_ANSWER,
  SPECTRALLOCK_FAQ_NAME,
  SPECTRALLOCK_SOFTWARES_LINE,
  RESEARCH_ADDENDUM,
  HARDWARE_ADDENDUM,
  PUBLISHED_RESEARCH,
  PUBLISHED_HARDWARE,
  LIBRARY_FRONT_DOOR_SNAPSHOT,
  WHO_IS_ANSWER,
  aboutPageNode,
  identityLockBlock,
  personAlternateNames,
  personNode,
  faqPageNode,
  sectionPageNodes,
  siteCoverageLines,
} from "./identity.js";
import {
  CITE_DONT_MERGE,
  INGEST_BYTES_HREF,
  INGEST_HREF,
  REEXPAND_HREF,
  VERIFY_HREF,
  ingestLlmsBlock,
  ingestRecord,
  nolieCite,
  survivalCite,
  survivalLlmsBlock,
} from "./ingest.js";
import {
  CHANNEL_PLANE,
  GET_IS_NODE_GATE,
  MESH_NOTE,
  NEIGHBOR_HEAL,
  NETWORK_CITE,
  NETWORK_ON,
  NODE_GATE,
  QNM_COMPANION,
  QNM_ENABLE_BEARER,
  QNM_SPEC,
  QNS_CD,
  QNS_CD_SPEC,
  VPN_CITE,
  WORKER_HARDWARE,
} from "./mesh.js";
import {
  CAP7_DESIGN_OF,
  CAP7_INHERIT,
  REDLINE_SPEC,
  attackSurfaceCite,
  foldlockTipSafeCite,
  redlineCiteField,
  redlineLlmsBlock,
  tlsCite,
} from "./redline.js";
import {
  SHELVES_HREF,
  SHELVES_JSON_HREF,
  SHELVES_PATH,
  SHELVES_JSON_PATH,
  cap7Cite,
  shelvesCite,
  shelvesLlmsBlock,
} from "./shelves.js";
import {
  BAN_SURVIVAL_SPEC,
  SURVIVAL_JSON_LOCAL,
  SURVIVAL_LOCAL,
  SURVIVAL_ORIGIN,
  SURVIVAL_RUNTIME,
  banSurvivalCite,
  survivalLlmsBlock as banSurvivalLlmsBlock,
} from "./survival.js";
import { HELP_SITEMAP_HREFS } from "./help.js";

export const AI_CRAWLER_AGENTS = [
  "GPTBot",
  "ChatGPT-User",
  "OAI-SearchBot",
  "Grok",
  "GrokBot",
  "Grok-DeepSearch",
  "xAI-SearchBot",
  "xAI-Bot",
  "xAI-Grok",
  "Venice",
  "Google-Extended",
  "Googlebot",
  "Google-InspectionTool",
  "GoogleOther",
  "Google-CloudVertexBot",
  "ClaudeBot",
  "Claude-SearchBot",
  "Claude-User",
  "Claude",
  "anthropic-ai",
  "PerplexityBot",
  "Perplexity-User",
  "bingbot",
  "Meta-ExternalAgent",
  "Meta-ExternalFetcher",
  "Meta-WebIndexer",
  "Applebot",
  "Applebot-Extended",
  "Amazonbot",
  "DuckDuckBot",
  "DuckAssistBot",
  "MistralAI-User",
  "YouBot",
  "CCBot",
  "cohere-ai",
  "cohere-training-data-crawler",
  "Diffbot",
  "AI2Bot",
  "AI2Bot-Dolma",
  "Timpibot",
  "Petalbot",
  "Bytespider",
  "Omgili",
  "Omgilibot",
  "FirecrawlAgent",
  "Cloudflare-AI-Search",
  "ImagesiftBot",
  "FacebookBot",
  "facebookexternalhit",
  "Meta-ExternalAds",
  "TikTokSpider",
  "Baiduspider",
  "Baiduspider-render",
  "Baiduspider-ai",
  "YandexBot",
  "PanguBot",
  "Kangaroo Bot",
  "Cotoyogi",
  "aiHitBot",
  "webzio-extended",
  "ICC-Crawler",
  "DataForSeoBot",
  "AwarioBot",
  "AwarioSmartBot",
  "AwarioRssBot",
  "Sentibot",
  "peer39_crawler",
  "Seekr",
  "Meltwater",
  "TurnitinBot",
  "Factset_spyderbot",
  "NeevaBot",
];

export const AI_CLIENTS = [
  "ChatGPT (GPT Actions / OpenAI)",
  "Grok (xAI)",
  "Venice",
  "Claude (Anthropic Desktop / custom tools)",
  "Cursor (MCP)",
  "Glama (Install Server / MCP)",
  "Perplexity",
  "Microsoft Copilot / Bing",
  "Google Gemini / Vertex AI",
  "Mistral",
  "Meta AI",
  "Apple Intelligence / Applebot surfaces",
  "Amazon Q / Amazonbot tooling",
  "DuckAssist / DuckDuckGo AI",
  "You.com",
  "Cohere",
];

export const AI_CLIENTS_SENTENCE =
  "Compatible clients: " + AI_CLIENTS.join(", ") + ", and other MCP/OpenAPI-capable assistants.";

export const CONTENT_SIGNAL = "search=yes, ai-input=yes, ai-train=yes";
export const ROBOTS_INDEX =
  "index,follow,max-image-preview:large,max-snippet:-1,max-video-preview:-1";

const PUBLIC_ALLOW = [
  "/",
  "/software",
  "/software/",
  "/why",
  "/why/",
  "/mission",
  "/mission/",
  "/research",
  "/research/",
  "/doors",
  "/doors/",
  "/receipts",
  "/receipts/",
  "/ingest",
  "/ingest/",
  "/ingest.txt",
  "/verify",
  "/verify/",
  "/reexpand",
  "/reexpand/",
  "/aziel",
  "/aziel/",
  "/about",
  "/about/",
  "/AzielEliab",
  "/AzielEliab/",
  "/aziel-eliab",
  "/aziel-eliab/",
  "/donate",
  "/donate/",
  "/donate/qr/",
  "/embryolock",
  "/embryolock/",
  "/sigil.png",
  "/cite.json",
  "/llms.txt",
  "/ai.txt",
  SHELVES_PATH,
  SHELVES_PATH + "/",
  SHELVES_JSON_PATH,
  "/person.jsonld",
  "/identity.jsonld",
  "/graph.jsonld",
  "/who-is-aziel-eliab.txt",
  "/who-is",
  "/who",
  "/who/",
  "/.well-known/aziel.json",
  "/.well-known/person.jsonld",
  "/sitemap.xml",
  "/robots.txt",
  "/v1/stats",
  "/v1/view",
  "/v1/software",
  "/v1/update",
  "/v1/update/check",
  "/v1/mesh/status",
  "/v1/mesh/nodes",
  "/survival",
  "/survival/",
  "/v1/survival",
  "/runtime",
  "/runtime/",
  "/runtime/openapi.json",
  "/runtime/mcp",
  "/runtime/v1/skill",
  "/runtime/v1/software",
  "/runtime/v1/fraggate/list",
  "/runtime/v1/uses",
  "/runtime/v1/mesh/status",
  "/runtime/v1/mesh/nodes",
  "/runtime/survival",
  "/runtime/v1/survival",
];

export function robotsTxt() {
  const star = ["User-agent: *", "Content-Signal: " + CONTENT_SIGNAL].concat(
    PUBLIC_ALLOW.map((p) => "Allow: " + p),
  );
  const bots = AI_CRAWLER_AGENTS.flatMap((agent) => ["", "User-agent: " + agent, "Allow: /"]);
  return star.concat(bots).concat(["", "Sitemap: " + CANON_ORIGIN + "/sitemap.xml", ""]).join("\n");
}

const SITEMAP_RANK = {
  [CANON_ORIGIN + "/"]: { changefreq: "daily", priority: "1.0" },
  [SOFTWARE_HREF]: { changefreq: "daily", priority: "0.9" },
  [CANON_ORIGIN + "/why"]: { changefreq: "weekly", priority: "0.7" },
  [CANON_ORIGIN + "/research"]: { changefreq: "weekly", priority: "0.7" },
  [CANON_ORIGIN + "/doors"]: { changefreq: "weekly", priority: "0.6" },
  [RECEIPTS_HREF]: { changefreq: "weekly", priority: "0.7" },
  [INGEST_HREF]: { changefreq: "weekly", priority: "0.7" },
  [INGEST_BYTES_HREF]: { changefreq: "weekly", priority: "0.6" },
  [VERIFY_HREF]: { changefreq: "weekly", priority: "0.6" },
  [REEXPAND_HREF]: { changefreq: "weekly", priority: "0.5" },
  [CANON_ORIGIN + "/aziel"]: { changefreq: "weekly", priority: "0.8" },
  [CANON_ORIGIN + "/about"]: { changefreq: "weekly", priority: "0.8" },
  [CANON_ORIGIN + "/AzielEliab"]: { changefreq: "weekly", priority: "0.8" },
  [CANON_ORIGIN + "/aziel-eliab"]: { changefreq: "weekly", priority: "0.7" },
  [DONATE_HREF]: { changefreq: "weekly", priority: "0.7" },
  [CANON_ORIGIN + "/donate"]: { changefreq: "weekly", priority: "0.7" },
  [CANON_ORIGIN + "/cite.json"]: { changefreq: "daily", priority: "0.6" },
  [CANON_ORIGIN + "/llms.txt"]: { changefreq: "daily", priority: "0.6" },
  [SHELVES_HREF]: { changefreq: "daily", priority: "0.6" },
  [SHELVES_JSON_HREF]: { changefreq: "daily", priority: "0.5" },
  [CANON_ORIGIN + "/person.jsonld"]: { changefreq: "weekly", priority: "0.8" },
  [CANON_ORIGIN + "/identity.jsonld"]: { changefreq: "weekly", priority: "0.8" },
  [CANON_ORIGIN + "/graph.jsonld"]: { changefreq: "weekly", priority: "0.8" },
  [CANON_ORIGIN + "/who-is-aziel-eliab.txt"]: { changefreq: "weekly", priority: "0.8" },
  [CANON_ORIGIN + "/who-is"]: { changefreq: "weekly", priority: "0.8" },
  [WHO_HREF]: { changefreq: "weekly", priority: "0.8" },
  [CANON_ORIGIN + "/.well-known/aziel.json"]: { changefreq: "weekly", priority: "0.8" },
  [CANON_ORIGIN + "/.well-known/person.jsonld"]: { changefreq: "weekly", priority: "0.7" },
  [CANON_ORIGIN + "/ai.txt"]: { changefreq: "weekly", priority: "0.5" },
  [CANON_ORIGIN + "/help.txt"]: { changefreq: "weekly", priority: "0.6" },
  [CANON_ORIGIN + "/addendum.txt"]: { changefreq: "weekly", priority: "0.5" },
  [CANON_ORIGIN + "/help/softwares.txt"]: { changefreq: "weekly", priority: "0.5" },
  [CANON_ORIGIN + "/help/receipts.txt"]: { changefreq: "weekly", priority: "0.5" },
  [CANON_ORIGIN + "/help/runtime.txt"]: { changefreq: "weekly", priority: "0.5" },
  [CANON_ORIGIN + "/v1/software"]: { changefreq: "hourly", priority: "0.8" },
  [SURVIVAL_LOCAL]: { changefreq: "hourly", priority: "0.6" },
  [SURVIVAL_JSON_LOCAL]: { changefreq: "hourly", priority: "0.5" },
  [RUNTIME_LOCAL]: { changefreq: "daily", priority: "0.8" },
  [TRADES_RUNTIME + "/"]: { changefreq: "daily", priority: "0.7" },
  [TRADES_RUNTIME_GITHUB]: { changefreq: "weekly", priority: "0.6" },
};

export function sitemapXml(now = new Date(), software = SOFTWARE) {
  const lastmod = now.toISOString().slice(0, 10);
  const doors = software && software.length ? software : SOFTWARE;
  const locs = [
    CANON_ORIGIN + "/",
    SOFTWARE_HREF,
    ...INDEXABLE_SECTIONS.map((s) => CANON_ORIGIN + s.path),
    ...ABOUT_PATHS.map((p) => CANON_ORIGIN + p),
    CANON_ORIGIN + "/donate",
    DONATE_HREF,
    RECEIPTS_HREF,
    INGEST_HREF,
    INGEST_BYTES_HREF,
    VERIFY_HREF,
    REEXPAND_HREF,
    EMBRYOLOCK_HREF,
    SIGIL,
    RUNTIME_LOCAL,
    RUNTIME_LOCAL + "/openapi.json",
    RUNTIME_LOCAL + "/v1/skill",
    RUNTIME_LOCAL + "/v1/software",
    RUNTIME_LOCAL + "/v1/fraggate/list",
    CANON_ORIGIN + "/cite.json",
    CANON_ORIGIN + "/llms.txt",
    SHELVES_HREF,
    SHELVES_JSON_HREF,
    CANON_ORIGIN + "/person.jsonld",
    CANON_ORIGIN + "/identity.jsonld",
    CANON_ORIGIN + "/graph.jsonld",
    CANON_ORIGIN + "/who-is-aziel-eliab.txt",
    CANON_ORIGIN + "/who-is",
    WHO_HREF,
    CANON_ORIGIN + "/.well-known/aziel.json",
    CANON_ORIGIN + "/.well-known/person.jsonld",
    CANON_ORIGIN + "/ai.txt",
    ...HELP_SITEMAP_HREFS,
    CANON_ORIGIN + "/robots.txt",
    CANON_ORIGIN + "/sitemap.xml",
    CANON_ORIGIN + "/v1/stats",
    CANON_ORIGIN + "/v1/view",
    CANON_ORIGIN + "/v1/software",
    CANON_ORIGIN + "/v1/update",
    CANON_ORIGIN + "/v1/update/check",
    CANON_ORIGIN + "/v1/mesh/status",
    CANON_ORIGIN + "/v1/mesh/nodes",
    SURVIVAL_LOCAL,
    SURVIVAL_JSON_LOCAL,
    RUNTIME_LOCAL + "/v1/uses",
    RUNTIME_LOCAL + "/v1/mesh/status",
    RUNTIME_LOCAL + "/v1/mesh/nodes",
    SURVIVAL_RUNTIME,
    RUNTIME_LOCAL + "/v1/survival",
    FRAGGATE,
    FRAGGATE_GITHUB,
    GITHUB,
    GITHUB_SECONDARY,
    GITHUB_SITE,
    GITHUB_RUNTIME,
    GITHUB_QNM_NODE,
    LIBRARY + "/",
    LIBRARY_AZIEL,
    LIBRARY_SOFTWARE,
    LIBRARY_RUNTIME,
    GODLOCK + "/",
    GODLOCK_AZIEL,
    HEDIDNTJUMP + "/",
    RUNTIME + "/",
    RUNTIME + "/v1/software",
    RUNTIME + "/v1/fraggate/list",
    TRADES_RUNTIME + "/",
    TRADES_RUNTIME_DOWNLOAD,
    TRADES_RUNTIME_OPENAPI,
    TRADES_RUNTIME_MCP,
    TRADES_RUNTIME_CITE,
    TRADES_RUNTIME_LLMS,
    TRADES_RUNTIME_SKILL,
    TRADES_RUNTIME_HEALTH,
    TRADES_RUNTIME_STATS,
    TRADES_RUNTIME_GITHUB,
    X_URL,
    ...doors.map((s) => s.href),
  ];
  const seen = new Set();
  const unique = [];
  for (const loc of locs) {
    if (!loc || seen.has(loc)) continue;
    seen.add(loc);
    unique.push(loc);
  }
  return (
    '<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n' +
    unique
      .map((u) => {
        const rank = SITEMAP_RANK[u];
        let inner = "<loc>" + u + "</loc><lastmod>" + lastmod + "</lastmod>";
        if (rank) {
          inner += "<changefreq>" + rank.changefreq + "</changefreq><priority>" + rank.priority + "</priority>";
        }
        return "  <url>" + inner + "</url>";
      })
      .join("\n") +
    "\n</urlset>\n"
  );
}

export function citeDoc(software = SOFTWARE, runtimeVersion = RUNTIME_VERSION, survival = null) {
  const doorsSoftware = software && software.length ? software : SOFTWARE;
  const version = resolveRuntimeVersion(runtimeVersion);
  const ingest = ingestRecord();
  const banSurvival = banSurvivalCite(survival);
  return {
    author: AUTHOR,
    identity: AUTHOR,
    title: SITE,
    site: CANON_ORIGIN + "/",
    canonical: CANON_ORIGIN + "/",
    about: ABOUT_HREF,
    about_aliases: ABOUT_PATHS.map((p) => CANON_ORIGIN + p),
    about_pages: ABOUT_ALIAS_HREFS.slice(),
    indexable_sections: INDEXABLE_SECTIONS.map((s) => {
      const row = {
        path: s.path,
        url: CANON_ORIGIN + s.path,
        title: s.title,
      };
      if (s.home) row.hash = "/#" + s.hash;
      else row.legacy_hash = "/#" + s.hash;
      return row;
    }),
    hash_redirects: Object.fromEntries(
      Object.entries(HASH_REDIRECTS).map(([hash, dest]) => ["#" + hash, CANON_ORIGIN + dest]),
    ),
    about_published: ABOUT_PUBLISHED_LINES.slice(),
    about_machine: ABOUT_MACHINE_HREFS.slice(),
    software_page: SOFTWARE_HREF,
    software_alias: SOFTWARE_HREF,
    software_section: SOFTWARE_HREF,
    software_title: SOFTWARE_TITLE,
    llms: CANON_ORIGIN + "/llms.txt",
    ai: CANON_ORIGIN + "/ai.txt",
    shelves: SHELVES_HREF,
    shelves_json: SHELVES_JSON_HREF,
    cold_multi_shelf: shelvesCite(),
    redline: redlineCiteField(),
    tls: tlsCite(),
    attack_surface: attackSurfaceCite(),
    cap7: {
      ...cap7Cite(),
      spec: "CAP-7",
      design_of: CAP7_DESIGN_OF,
      inherit: CAP7_INHERIT,
      resolves_to_hub: false,
    },
    design_of: CAP7_DESIGN_OF,
    resolves_to_hub: false,
    ban_survival: banSurvival,
    calling_name: banSurvival.calling_name,
    calling_name_alert: banSurvival.calling_name_alert,
    platforms: banSurvival.platforms,
    mesh_live_nodes_are_api: false,
    godlock_is_product_not_identity: true,
    visible_1520: false,
    foldlock: foldlockTipSafeCite(),
    foldlock_shelf: "FOLDLOCK-SHELF-1.0",
    spectrallock: spectrallockCite(),
    person_jsonld: CANON_ORIGIN + "/person.jsonld",
    identity_jsonld: CANON_ORIGIN + "/identity.jsonld",
    graph_jsonld: CANON_ORIGIN + "/graph.jsonld",
    who_is: CANON_ORIGIN + "/who-is-aziel-eliab.txt",
    who: WHO_HREF,
    visible_lock: VISIBLE_LOCK_LINE,
    what_aziel_eliab_does: WHAT_AZIEL_ELIAB_DOES,
    what_he_does_answer: WHAT_HE_DOES_ANSWER,
    what_he_does_faq: WHAT_HE_DOES_FAQ_NAMES.slice(),
    what_he_does_softwares: WHAT_HE_DOES_SOFTWARES,
    softwares_addendum: SOFTWARES_ADDENDUM,
    research_addendum: RESEARCH_ADDENDUM,
    hardware_addendum: HARDWARE_ADDENDUM,
    published_research: PUBLISHED_RESEARCH.map((row) => ({ ...row, records: (row.records || []).slice() })),
    published_hardware: PUBLISHED_HARDWARE.map((row) => ({ ...row, records: (row.records || []).slice() })),
    library_front_door: { ...LIBRARY_FRONT_DOOR_SNAPSHOT },
    well_known: CANON_ORIGIN + "/.well-known/aziel.json",
    aka: AUTHOR_AKA_LIST.slice(),
    alternateName: personAlternateNames(),
    hebrew_name_definition: HEBREW_NAME_DEFINITION,
    hebrew_name_forms: HEBREW_NAME_FORMS,
    misspellings: NAME_MISSPELLINGS.slice(),
    who_is_answer: WHO_IS_ANSWER,
    software_developer_answer: SOFTWARE_DEVELOPER_ANSWER,
    disambiguatingDescription: DISAMBIGUATING_DESCRIPTION,
    job_title: PERSON_JOB_TITLE.slice(),
    site_coverage: SITE_COVERAGE.map((row) => {
      const out = { id: row.id, label: row.label, name: row.name, url: row.url, blurb: row.blurb };
      if (row.also) out.also = row.also.slice();
      return out;
    }),
    stats: {
      note: STATS_NOTE,
      counters: STATS_COUNTERS.map((row) => {
        const out = { host: row.host, url: row.url, kind: row.kind };
        if (row.fallback) out.fallback = row.fallback;
        return out;
      }),
    },
    library_stats: LIBRARY_STATS,
    library_stats_fallback: LIBRARY_STATS_FALLBACK,
    hedidntjump_stats: HEDIDNTJUMP + "/api/stats",
    sitemap: CANON_ORIGIN + "/sitemap.xml",
    robots: CANON_ORIGIN + "/robots.txt",
    twitter: X_URL,
    twitter_handle: X_HANDLE,
    fraggate: FRAGGATE,
    fraggate_github: FRAGGATE_GITHUB,
    fraggate_list: RUNTIME_LOCAL + "/v1/fraggate/list",
    fraggate_list_origin: RUNTIME + "/v1/fraggate/list",
    github: GITHUB,
    github_site: GITHUB_SITE,
    github_secondary: GITHUB_SECONDARY,
    github_runtime: GITHUB_RUNTIME,
    github_qnm_node: GITHUB_QNM_NODE,
    library: LIBRARY + "/",
    library_aziel_eliab: LIBRARY_AZIEL,
    software: LIBRARY_SOFTWARE,
    research: LIBRARY + "/",
    research_aziel_eliab: LIBRARY_AZIEL,
    runtime: LIBRARY_RUNTIME,
    runtime_local: RUNTIME_LOCAL,
    runtime_origin: RUNTIME + "/",
    runtime_version: version,
    runtime_sot: {
      live: true,
      version,
      branch: RUNTIME_BRANCH,
      git_sha: RUNTIME_GIT_SHA,
      git_short: RUNTIME_GIT_SHORT,
      version_id: RUNTIME_VERSION_ID,
      origin: RUNTIME + "/",
      note: "Runtime SoT LIVE: main " + RUNTIME_GIT_SHORT + " / version_id " + RUNTIME_VERSION_ID + " / " + version + " at " + RUNTIME,
    },
    runtime_git_sha: RUNTIME_GIT_SHA,
    runtime_git_short: RUNTIME_GIT_SHORT,
    runtime_version_id: RUNTIME_VERSION_ID,
    runtime_download: RUNTIME_DOWNLOAD,
    runtime_download_v1: RUNTIME_DOWNLOAD_V1,
    runtime_download_note: RUNTIME_DOWNLOAD_NOTE,
    runtime_human_ui: RUNTIME_HUMAN_UI,
    dual_surface: DUAL_SURFACE,
    mcp: {
      door: "fraggate",
      softwares: "fraggate_call only",
      master_33: MASTER_33_MCP,
      : FIELD_100,
      note: DUAL_SURFACE.agent,
    },
    : FIELD_100,
    master_33: MASTER_33_MCP,
    glama_runtime: GLAMA_RUNTIME,
    runtime_docs: RUNTIME_DOCS,
    runtime_doors: RUNTIME_DOORS.map((d) => ({
      label: d.label,
      url: d.href,
      primary: Boolean(d.primary),
    })),
    godlock: GODLOCK + "/",
    godlock_aziel_eliab: GODLOCK_AZIEL,
    hedidntjump: HEDIDNTJUMP + "/",
    x: X_URL,
    donate: DONATE_HREF,
    views: CANON_ORIGIN + "/v1/stats",
    view_increment: CANON_ORIGIN + "/v1/view",
    software_catalog: CANON_ORIGIN + "/v1/software",
    software_catalog_local: RUNTIME_LOCAL + "/v1/software",
    software_catalog_origin: RUNTIME + "/v1/software",
    software_catalog_fallback: RUNTIME + "/v1/fraggate/list",
    software_catalog_fallback_local: RUNTIME_LOCAL + "/v1/fraggate/list",
    runtime_openapi: RUNTIME_LOCAL + "/openapi.json",
    runtime_mcp: RUNTIME_LOCAL + "/mcp",
    runtime_skill: RUNTIME_LOCAL + "/v1/skill",
    update_check: CANON_ORIGIN + "/v1/update/check",
    update_check_origin: RUNTIME + "/v1/update/check",
    mesh_status: CANON_ORIGIN + "/v1/mesh/status",
    mesh_nodes: CANON_ORIGIN + "/v1/mesh/nodes",
    mesh_status_runtime: RUNTIME_LOCAL + "/v1/mesh/status",
    mesh_nodes_runtime: RUNTIME_LOCAL + "/v1/mesh/nodes",
    mesh_status_origin: RUNTIME + "/v1/mesh/status",
    mesh_nodes_origin: RUNTIME + "/v1/mesh/nodes",
    mesh_default: "on",
    mesh_note: MESH_NOTE,
    node_gate: NODE_GATE,
    get_is_node_gate: GET_IS_NODE_GATE,
    neighbor_heal: NEIGHBOR_HEAL,
    network: NETWORK_ON,
    network_cite: NETWORK_CITE,
    worker_hardware: WORKER_HARDWARE,
    channel_plane: CHANNEL_PLANE,
    vpn: VPN_CITE,
    login_mesh: false,
    qnm_spec: QNM_SPEC,
    qnm_companion: QNM_COMPANION,
    mesh_enable_bearer: QNM_ENABLE_BEARER,
    mesh_get_never_enables: true,
    qns_cd_spec: QNS_CD_SPEC,
    qns_cd: QNS_CD,
    runtime_uses: RUNTIME_LOCAL + "/v1/uses",
    brandmark: SIGIL,
    brandmark_name: BRANDMARK_NAME,
    sigil: SIGIL,
    license: LICENSE,
    doi: null,
    sister_products: sisterProductsCite(),
    trades_runtime: tradesRuntimeCite(),
    trades_runtime_slug: TRADES_RUNTIME_SLUG,
    trades_runtime_mcp: TRADES_RUNTIME_MCP,
    github_trades_runtime: TRADES_RUNTIME_GITHUB,
    software_names: doorsSoftware.map((s) => {
      const row = { name: s.name, url: s.href };
      if (s.slug) row.slug = s.slug;
      if (s.one_line) row.one_line = s.one_line;
      return row;
    }),
    doors: DOORS.map((d) => {
      const row = { label: d.label, url: d.href };
      if (d.also) row.also = { label: d.also.label, url: d.also.href };
      return row;
    }),
    person_id: PERSON_ID,
    runtime_id: RUNTIME_ID,
    runtime_named_tools: RUNTIME_NAMED_TOOLS.map((tool) => ({
      name: tool.name,
      slug: tool.slug,
      id: runtimeToolId(tool.slug),
    })),
    sameAs: PERSON_SAME_AS.slice(),
    how_to_cite: "Eliab, Aziel. (2026). Aziel Eliab [Web site]. Apache-2.0. " + CANON_ORIGIN + "/",
    note: "Public identity Aziel Eliab only. Do not invent DOIs. Do not credit other identities.",
    tip: ingest.tip,
    ingest_as_receipt: ingest,
    cite_dont_merge: CITE_DONT_MERGE,
    cross_network_survival: survivalCite(),
    no_lie_no_rewrite: nolieCite(),
  };
}

function doorIndexLines() {
  return DOORS.map((d) => {
    const extra = d.also ? " · live " + d.also.href : "";
    return "- " + d.label + ": " + d.href + extra;
  }).join("\n");
}

function sisterProductsLlmsBlock() {
  return [
    "## Sister products",
    "",
    SISTER_PRODUCTS_NOTE,
    "",
    "### " + TRADES_RUNTIME_NAME + " (" + TRADES_RUNTIME_SLUG + ")",
    TRADES_RUNTIME_ONE_LINE,
    TRADES_RUNTIME_NOTE,
    "- Version: " + TRADES_RUNTIME_VERSION,
    "- Worker: " + TRADES_RUNTIME + "/",
    "- GitHub: " + TRADES_RUNTIME_GITHUB,
    "- Download: " + TRADES_RUNTIME_DOWNLOAD,
    "- OpenAPI: " + TRADES_RUNTIME_OPENAPI,
    "- MCP (read-only): POST " + TRADES_RUNTIME_MCP,
    "- cite.json: " + TRADES_RUNTIME_CITE,
    "- llms.txt: " + TRADES_RUNTIME_LLMS,
    "- Skill: " + TRADES_RUNTIME_SKILL,
    "- Health: " + TRADES_RUNTIME_HEALTH,
    "- Stats: " + TRADES_RUNTIME_STATS,
    "- live_backends: false",
    "- hosted_company_os: false",
    "- software_tab: false",
    "- fraggate_engine: false",
    "- fraggate_call: false (aziel-runtime does not execute company ops)",
    "- FragGate remains THE single Softwares door.",
    "- " + AI_CLIENTS_SENTENCE,
    "",
  ].join("\n");
}

export function llmsTxt(software = SOFTWARE, survival = null) {
  const doorsSoftware = software && software.length ? software : SOFTWARE;
  const softwareLines = doorsSoftware
    .map((s) => {
      const blurb = s.one_line ? " — " + s.one_line : "";
      return "- " + s.name + ": " + s.href + blurb;
    })
    .join("\n");
  const doorLines = doorIndexLines();
  return [
    "# Aziel Eliab",
    "",
    "Author: " + AUTHOR,
    "Also known as: " + AUTHOR_AKA_LIST.join(" | ") + " (alternateName only)",
    "Primary credit: " + AUTHOR,
    "Canonical: " + CANON_ORIGIN + "/",
    "Apex: https://azieleliab.com/ (redirects to www)",
    "GitHub: " + GITHUB_SITE,
    "License: " + LICENSE,
    "DOI: none (do not invent)",
    "",
    ingestRecord().tip,
    CITE_DONT_MERGE,
    "",
    identityLockBlock(),
    "",
    "Purpose: Public landing for Aziel Eliab. You don’t get to know me. You get to understand the work.",
    "Identity is Aziel Eliab only.",
    "",
    "## Identity",
    "",
    "- Primary author: " + AUTHOR,
    "- Alternate name / aka: " + AUTHOR_AKA_LIST.join(" | "),
    "- About (this origin): " + ABOUT_HREF + " (aliases " + ABOUT_PATHS.map((p) => CANON_ORIGIN + p).join(", ") + " 301 here)",
    "- About machine: " + ABOUT_MACHINE_HREFS.join(" · "),
    "- Profile (library): " + LIBRARY_AZIEL,
    "- GodLock identity: " + GODLOCK_AZIEL,
    "- He Didn't Jump: " + HEDIDNTJUMP + "/",
    "- Person @id: " + PERSON_ID,
    "- Hebrew name: " + HEBREW_NAME_DEFINITION,
    "- Runtime parent @id: " + RUNTIME_ID,
    "- Named tools: " + RUNTIME_NAMED_TOOLS.map((t) => t.name).join(", "),
    "- sameAs: " + PERSON_SAME_AS.join(" · "),
    "- jobTitle: " + PERSON_JOB_TITLE.join(" | "),
    "",
    "## Site coverage",
    "",
    ...siteCoverageLines(),
    "",
    "## Mission",
    "",
    ...ABOUT_PUBLISHED_LINES.map((line) => "- " + line),
    "",
    "## Research",
    "",
    "- Research door: " + LIBRARY + "/",
    "- Library identity: " + LIBRARY_AZIEL,
    "- The research corpus lives at the Digital Library.",
    "",
    "## Software",
    "",
    "- Softwares list: " + SOFTWARE_HREF,
    "- Softwares page: " + SOFTWARE_HREF + " (distinct Software page; /#software maps here)",
    "- Softwares: " + WHAT_HE_DOES_SOFTWARES,
    "- Softwares note: " + SOFTWARES_ADDENDUM,
    "- Live catalog (this host): " + CANON_ORIGIN + "/v1/software",
    "- Live catalog (aziel-runtime): " + RUNTIME + "/v1/software",
    "- FragGate list: " + RUNTIME_LOCAL + "/v1/fraggate/list (origin " + RUNTIME + "/v1/fraggate/list)",
    "- FragGate Worker: " + FRAGGATE,
    "- FragGate kernel: " + FRAGGATE_GITHUB,
    "",
    softwareLines,
    "- Softwares note: " + SOFTWARES_ADDENDUM,
    SPECTRALLOCK_SOFTWARES_LINE,
    "- SpectralLock FAQ: " + SPECTRALLOCK_FAQ_NAME,
    "- SpectralLock FAQ answer: " + SPECTRALLOCK_FAQ_ANSWER,
    "- SpectralLock unredact: GET|POST " + SPECTRALLOCK_UNREDACT + " (deep PDF + revision_graph + per-revision copies)",
    "- SpectralLock recover: GET|POST " + SPECTRALLOCK_RECOVER + " (universal artifact recover; NO-LIE; LIVE vs SLOT)",
    "- SpectralLock handwriting: GET|POST " + SPECTRALLOCK_HANDWRITING + " (physical ink scan heuristics)",
    "- SpectralLock OCR: " + SPECTRALLOCK_OCR_NOTE,
    "",
    "## " + RUNTIME_TITLE,
    "",
    "- Parent @id: " + RUNTIME_ID,
    "- Named tools: " + RUNTIME_NAMED_TOOLS.map((t) => t.name).join(", "),
    "- " + RUNTIME_NAME + ": " + RUNTIME_LOCAL,
    "- Version: " + RUNTIME_VERSION + " (live GET " + RUNTIME + "/v1/health)",
    "- SoT LIVE: main " + RUNTIME_GIT_SHORT + " / version_id " + RUNTIME_VERSION_ID + " / " + RUNTIME_VERSION + " at " + RUNTIME,
    "- Try on Glama: " + GLAMA_RUNTIME,
    "- Official Runtime: " + RUNTIME + "/",
    "- Suite pack: " + RUNTIME_DOWNLOAD + " (GET /download)",
    "- Source on GitHub: " + GITHUB_RUNTIME,
    "- Documentation / Architecture: " + RUNTIME_DOCS,
    "- Origin: " + RUNTIME + "/",
    "- Library: " + LIBRARY_RUNTIME,
    "- Live catalog: " + RUNTIME + "/v1/software (fallback " + RUNTIME + "/v1/fraggate/list)",
    "- Softwares tab: heading → name list only. Plain A–Z → Gate A–Z → Lock A–Z.",
    "- MCP: Softwares via fraggate_call only. FragGate sole door. master_33:false. :false.",
    "- Dual surface: agent MCP + complete human UI on runtime (#op-panel / #dashboard / #fg-console + #task-* + About Aziel + per-product hashtags + GET /download).",
    "- OpenAPI: " + RUNTIME_LOCAL + "/openapi.json",
    "- MCP: POST " + RUNTIME_LOCAL + "/mcp",
    "- Skill: " + RUNTIME_LOCAL + "/v1/skill",
    "- FragGate list: " + RUNTIME_LOCAL + "/v1/fraggate/list",
    "- Uses (this host's /runtime API stats): " + RUNTIME_LOCAL + "/v1/uses",
    "- Mesh status: " + RUNTIME_LOCAL + "/v1/mesh/status (QNM-BUILD-1.0 suite rollup; live_nodes = presence; GET never enables)",
    "- Mesh nodes: " + RUNTIME_LOCAL + "/v1/mesh/nodes",
    "- Operator enable requires a declared bearer (example: suite-presence). Read-only suite presence is on (display from runtime).",
    "- Mesh ON. Operator-armed Node Gate + neighbor heal + network ON.",
    "- AZVPN auto_use + vpn:true (HTTPS/WS REAL; WireGuard/OpenVPN SLOT). GET cites only.",
    "- Channel plane wifi/bluetooth/rf/photon ON cites; worker_hardware:false.",
    "- QNS-CD-1.0: " + QNS_CD_SPEC + " photon QNS1 packet transfer. Local qnsd in qnm-node. Skill: " + RUNTIME_LOCAL + "/v1/skill",
    "- " + AI_CLIENTS_SENTENCE,
    "",
    sisterProductsLlmsBlock(),
    "## Donate",
    "",
    "- " + DONATE_TITLE + ": " + DONATE_HREF,
    "- " + DONATE_DISCLAIMER,
    "- Static door. No Worker KV.",
    "",
    "## Doors",
    "",
    doorLines,
    "",
    ingestLlmsBlock(),
    shelvesLlmsBlock(),
    banSurvivalLlmsBlock(survival),
    redlineLlmsBlock(),
    "## Compatible AI clients",
    "",
    ...AI_CLIENTS.map((c) => "- " + c),
    "- plus other MCP/OpenAPI-capable assistants",
    "",
    "## Machine routes",
    "",
    "- GET " + CANON_ORIGIN + "/",
    "- GET " + SOFTWARE_HREF + "  (distinct Software page; /#software maps here)",
    "- GET " + CANON_ORIGIN + "/mission  (301 to / ; Mission/Status strip removed)",
    "- GET " + CANON_ORIGIN + "/why  (distinct Why page; /#why maps here)",
    "- GET " + CANON_ORIGIN + "/research  (distinct Research page; /#research maps here)",
    "- GET " + CANON_ORIGIN + "/doors  (distinct Doors page; /#doors maps here)",
    "- GET " + RECEIPTS_HREF + "  (ACT-RECEIPT-1.0 Receipts tab)",
    "- GET " + INGEST_HREF + "  (" + ingestRecord().spec + " first-screen law)",
    "- GET " + INGEST_BYTES_HREF + "  (canonical page bytes)",
    "- GET " + VERIFY_HREF + "  (paste-hash yes/no vs published tip)",
    "- GET " + REEXPAND_HREF + "  (" + ingestRecord().reexpand + "; crawlers do not re-expand)",
    "- GET " + CANON_ORIGIN + "/aziel  (200 same homepage; Person #aziel)",
    "- GET " + CANON_ORIGIN + "/about  (200 same homepage — About Aziel Eliab)",
    "- GET " + CANON_ORIGIN + "/AzielEliab  (200 same homepage)",
    "- GET " + CANON_ORIGIN + "/aziel-eliab  (200 same homepage)",
    "- GET " + DONATE_HREF + "  (AZL-DONATE-1.0 primary Donate door)",
    "- GET " + EMBRYOLOCK_HREF + "  (EmbryoLock secondary local page)",
    "- GET " + CANON_ORIGIN + "/sigil.png  (hosted rose-star brand mark)",
    "- GET " + CANON_ORIGIN + "/v1/software  (resolved live doors; products + extras)",
    "- GET " + CANON_ORIGIN + "/v1/update/check  (quiet installer pointer)",
    "- GET " + CANON_ORIGIN + "/v1/mesh/status  (QNM-BUILD-1.0 suite rollup; live_nodes = presence; GET never enables; suite-presence operator enable)",
    "- GET " + CANON_ORIGIN + "/v1/mesh/nodes",
    "- GET " + SURVIVAL_LOCAL + "  (" + BAN_SURVIVAL_SPEC + " hub pull of runtime SoT; short TTL)",
    "- GET " + SURVIVAL_JSON_LOCAL,
    "- GET " + CANON_ORIGIN + "/cite.json  (" + REDLINE_SPEC + " · Cap-7 design_of · attack-surface · FoldLock tip-safe · SpectralLock leftover-bytes + recover/handwriting · " + BAN_SURVIVAL_SPEC + ")",
    "- GET " + CANON_ORIGIN + "/llms.txt",
    "- GET " + SHELVES_HREF + "  (COLD-MULTI-SHELF-1.0; canonical registry " + shelvesCite().canonical_registry + ")",
    "- GET " + SHELVES_JSON_HREF,
    "- GET " + CANON_ORIGIN + "/person.jsonld",
    "- GET " + CANON_ORIGIN + "/identity.jsonld",
    "- GET " + CANON_ORIGIN + "/graph.jsonld",
    "- GET " + CANON_ORIGIN + "/who-is-aziel-eliab.txt",
    "- GET " + CANON_ORIGIN + "/who-is",
    "- GET " + WHO_HREF,
    "- GET " + CANON_ORIGIN + "/.well-known/aziel.json",
    "- GET " + CANON_ORIGIN + "/.well-known/person.jsonld",
    "- GET " + CANON_ORIGIN + "/ai.txt",
    "- GET " + CANON_ORIGIN + "/robots.txt",
    "- GET " + CANON_ORIGIN + "/sitemap.xml",
    "- GET " + RUNTIME_LOCAL,
    "- GET " + RUNTIME_LOCAL + "/openapi.json",
    "- GET " + RUNTIME_LOCAL + "/v1/skill",
    "- GET " + RUNTIME_LOCAL + "/v1/software",
    "- GET " + RUNTIME_LOCAL + "/v1/fraggate/list",
    "- POST " + RUNTIME_LOCAL + "/mcp",
    "- GET " + RUNTIME_LOCAL + "/v1/uses  (this host's /runtime API use stats)",
    "- GET " + RUNTIME_LOCAL + "/v1/mesh/status  (QNM-BUILD-1.0 suite rollup; live_nodes = presence; GET never enables)",
    "- GET " + RUNTIME_LOCAL + "/v1/mesh/nodes",
    "- GET " + SURVIVAL_RUNTIME + "  (" + BAN_SURVIVAL_SPEC + ")",
    "- GET " + RUNTIME_LOCAL + "/v1/survival",
    "- GET " + TRADES_RUNTIME + "/  (sister product Trades-Runtime)",
    "- GET " + TRADES_RUNTIME_DOWNLOAD,
    "- GET " + TRADES_RUNTIME_OPENAPI,
    "- POST " + TRADES_RUNTIME_MCP,
    "- GET " + TRADES_RUNTIME_CITE,
    "- GET " + TRADES_RUNTIME_LLMS,
    "- GET " + TRADES_RUNTIME_SKILL,
    "- GET " + TRADES_RUNTIME_GITHUB,
    "- GET " + CANON_ORIGIN + "/v1/stats  (read pageviews, no increment)",
    "- GET " + CANON_ORIGIN + "/v1/view   (read pageviews, no increment)",
    "- POST " + CANON_ORIGIN + "/v1/view  (increment pageviews)",
    "",
    "HTML GET / increments once for non-bot User-Agents when KV VIEWS is bound.",
    "",
    "Always send User-Agent Mozilla/5.0. Author Aziel Eliab only.",
    "",
  ].join("\n");
}

export function aiTxt(survival = null) {
  const bots = AI_CRAWLER_AGENTS.flatMap((agent) => ["", "User-agent: " + agent, "Allow: /"]);
  return [
    "# Aziel Eliab — AI crawl policy",
    "# Complement of /llms.txt. Author Aziel Eliab (aka Aziel Elroi Eliab).",
    "# Primary credit: Aziel Eliab. Do not invent DOIs.",
    "#",
    "# Allow the public landing and same-origin /runtime aziel-runtime door.",
    "",
    "User-agent: *",
    "Allow: /",
    "Allow: /software",
    "Allow: /software/",
    "Allow: /why",
    "Allow: /why/",
    "Allow: /mission",
    "Allow: /mission/",
    "Allow: /research",
    "Allow: /research/",
    "Allow: /doors",
    "Allow: /doors/",
    "Allow: /receipts",
    "Allow: /receipts/",
    "Allow: /ingest",
    "Allow: /ingest/",
    "Allow: /ingest.txt",
    "Allow: /verify",
    "Allow: /verify/",
    "Allow: /reexpand",
    "Allow: /reexpand/",
    "Allow: /aziel",
    "Allow: /aziel/",
    "Allow: /about",
    "Allow: /about/",
    "Allow: /AzielEliab",
    "Allow: /AzielEliab/",
    "Allow: /aziel-eliab",
    "Allow: /aziel-eliab/",
    "Allow: /donate",
    "Allow: /donate/",
    "Allow: /donate/qr/",
    "Allow: /embryolock",
    "Allow: /embryolock/",
    "Allow: /sigil.png",
    "Allow: /cite.json",
    "Allow: /llms.txt",
    "Allow: /ai.txt",
    "Allow: " + SHELVES_PATH,
    "Allow: " + SHELVES_PATH + "/",
    "Allow: " + SHELVES_JSON_PATH,
    "Allow: /person.jsonld",
    "Allow: /identity.jsonld",
    "Allow: /graph.jsonld",
    "Allow: /who-is-aziel-eliab.txt",
    "Allow: /who-is",
    "Allow: /who",
    "Allow: /who/",
    "Allow: /.well-known/aziel.json",
    "Allow: /.well-known/person.jsonld",
    "Allow: /robots.txt",
    "Allow: /sitemap.xml",
    "Allow: /v1/stats",
    "Allow: /v1/view",
    "Allow: /v1/software",
    "Allow: /v1/update",
    "Allow: /v1/update/check",
    "Allow: /v1/mesh/status",
    "Allow: /v1/mesh/nodes",
    "Allow: /survival",
    "Allow: /survival/",
    "Allow: /v1/survival",
    "Allow: /runtime",
    "Allow: /runtime/",
    "Allow: /runtime/openapi.json",
    "Allow: /runtime/mcp",
    "Allow: /runtime/v1/skill",
    "Allow: /runtime/v1/software",
    "Allow: /runtime/v1/fraggate/list",
    "Allow: /runtime/v1/uses",
    "Allow: /runtime/v1/mesh/status",
    "Allow: /runtime/v1/mesh/nodes",
    "Allow: /runtime/survival",
    "Allow: /runtime/v1/survival",
    "",
    "Content-Signal: " + CONTENT_SIGNAL,
    "",
    "User-agent: Googlebot",
    "Allow: /",
    ...bots,
    "",
    "Sitemap: " + CANON_ORIGIN + "/sitemap.xml",
    "",
    "## Research surfaces",
    "",
    "- Landing: " + CANON_ORIGIN + "/",
    "- About: " + ABOUT_HREF + " (aliases /about /AzielEliab /aziel-eliab)",
    "- Softwares: " + SOFTWARE_HREF + " (distinct page; /#software maps here)",
    "- Softwares: " + WHAT_HE_DOES_SOFTWARES,
    "- Softwares note: " + SOFTWARES_ADDENDUM,
    SPECTRALLOCK_SOFTWARES_LINE,
    "- SpectralLock FAQ: " + SPECTRALLOCK_FAQ_NAME,
    "- SpectralLock leftover-bytes: leftover_bytes / recovered_from; opaque rewrite refuses SL-UNREDACT-OPAQUE; inject ON is paint; never OCR-from-black-box",
    "- SpectralLock unredact: GET|POST " + SPECTRALLOCK_UNREDACT + " (deep PDF + revision_graph + per-revision copies)",
    "- SpectralLock recover: GET|POST " + SPECTRALLOCK_RECOVER + " (universal artifact recover; NO-LIE; LIVE vs SLOT)",
    "- SpectralLock handwriting: GET|POST " + SPECTRALLOCK_HANDWRITING + " (physical ink scan heuristics)",
    "- SpectralLock OCR: " + SPECTRALLOCK_OCR_NOTE,
    "- SpectralLock Worker: " + SPECTRALLOCK_WORKER,
    "- Receipts: " + RECEIPTS_HREF,
    "- Ingest: " + INGEST_HREF,
    "- Page bytes: " + INGEST_BYTES_HREF,
    "- Verify: " + VERIFY_HREF,
    "- Re-expand law: " + REEXPAND_HREF + " (crawlers do not re-expand)",
    "- Tip: " + ingestRecord().tip,
    "- " + CITE_DONT_MERGE,
    "",
    survivalLlmsBlock(),
    banSurvivalLlmsBlock(survival),
    "- Software catalog: " + CANON_ORIGIN + "/v1/software",
    "- FragGate list: " + RUNTIME_LOCAL + "/v1/fraggate/list",
    "- FragGate Worker: " + FRAGGATE,
    "- Donate: " + DONATE_HREF,
    "- Research / corpus: " + LIBRARY + "/",
    "- Library identity: " + LIBRARY_AZIEL,
    "- cite.json: " +
      CANON_ORIGIN +
      "/cite.json  (" +
      REDLINE_SPEC +
      " · Cap-7 design_of · attack-surface · FoldLock tip-safe · SpectralLock leftover-bytes + recover/handwriting)",
    "- llms.txt: " + CANON_ORIGIN + "/llms.txt",
    shelvesLlmsBlock(),
    redlineLlmsBlock(),
    "- shelves: " + SHELVES_HREF,
    "- shelves JSON: " + SHELVES_JSON_HREF,
    "- Software hub: " + LIBRARY_SOFTWARE,
    "- Aziel Runtime (aziel-runtime): " + RUNTIME_LOCAL,
    "- Runtime version: " + RUNTIME_VERSION + " (live GET " + RUNTIME + "/v1/health)",
    "- SoT LIVE: main " + RUNTIME_GIT_SHORT + " / version_id " + RUNTIME_VERSION_ID + " / " + RUNTIME_VERSION + " at " + RUNTIME,
    "- Try on Glama: " + GLAMA_RUNTIME,
    "- Official Runtime: " + RUNTIME + "/",
    "- Suite pack: " + RUNTIME_DOWNLOAD + " (GET /download)",
    "- Source on GitHub: " + GITHUB_RUNTIME,
    "- Documentation / Architecture: " + RUNTIME_DOCS,
    "- Runtime uses (this host): " + RUNTIME_LOCAL + "/v1/uses",
    "- Mesh status: " + CANON_ORIGIN + "/v1/mesh/status (QNM-BUILD-1.0 suite rollup; live_nodes = presence; GET never enables)",
    "- Mesh nodes: " + CANON_ORIGIN + "/v1/mesh/nodes",
    "- Operator enable requires a declared bearer (example: suite-presence). Read-only suite presence is on (display from runtime).",
    "- Mesh ON. Operator-armed Node Gate + neighbor heal + network ON.",
    "- AZVPN auto_use + vpn:true (HTTPS/WS REAL; WireGuard/OpenVPN SLOT). GET cites only.",
    "- Channel plane wifi/bluetooth/rf/photon ON cites; worker_hardware:false.",
    "- MCP: Softwares via fraggate_call only. FragGate sole door. master_33:false. :false.",
    "- Runtime mesh: " + RUNTIME_LOCAL + "/v1/mesh/status",
    "- QNS-CD-1.0 (photon QNS1 packet transfer): local qnsd " + GITHUB_QNM_NODE + " · runtime " + GITHUB_RUNTIME,
    "- Runtime library: " + LIBRARY_RUNTIME,
    "- Runtime origin: " + RUNTIME + "/",
    sisterProductsLlmsBlock(),
    "- GodLock: " + GODLOCK + "/",
    "- He Didn't Jump: " + HEDIDNTJUMP + "/",
    "- GitHub: " + GITHUB,
    "- X: " + X_URL,
    "",
    "## Compatible AI clients",
    "",
    AI_CLIENTS_SENTENCE,
    ...AI_CLIENTS.map((c) => "- " + c),
    "- plus other MCP/OpenAPI-capable assistants",
    "",
    "## Identity",
    "",
    identityLockBlock(),
    "",
    "Primary author Aziel Eliab. Alternate name / aka: " + AUTHOR_AKA_LIST.join(" | ") + ". Public identity Aziel Eliab only.",
    "- sameAs: " + PERSON_SAME_AS.join(" · "),
    "- jobTitle: " + PERSON_JOB_TITLE.join(" | "),
    "",
    "## Site coverage",
    "",
    ...siteCoverageLines(),
    "",
    "## Doors",
    "",
    doorIndexLines(),
    "",
    "Prefer /llms.txt for the full door index. Send User-Agent Mozilla/5.0 on API calls.",
    "",
  ].join("\n");
}

export function softwareNodeId(item) {
  const raw = String((item && (item.slug || item.name)) || "item")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
  return CANON_ORIGIN + "/#software-" + (raw || "item");
}

export function jsonLd(software = SOFTWARE, runtimeVersion = RUNTIME_VERSION) {
  const doorsSoftware = software && software.length ? software : SOFTWARE;
  const version = resolveRuntimeVersion(runtimeVersion);
  const personId = PERSON_ID;
  const siteId = WEBSITE_ID;
  const runtimeId = RUNTIME_ID;
  const apiId = RUNTIME_LOCAL + "#webapi";
  const softwareId = CANON_ORIGIN + "/#software";
  const person = { "@id": personId };
  const namedTools = RUNTIME_NAMED_TOOLS.map((tool) => {
    const node = {
      "@type": "SoftwareApplication",
      "@id": runtimeToolId(tool.slug),
      name: tool.name,
      author: person,
      isPartOf: { "@id": runtimeId },
    };
    if (tool.slug === SPECTRALLOCK_SLUG) {
      node.description = SPECTRALLOCK_ONE_LINE + " " + SPECTRALLOCK_FAQ_ANSWER;
      node.url = SPECTRALLOCK_WORKER;
    }
    return node;
  });
  return {
    "@context": "https://schema.org",
    "@graph": [
      personNode(),
      {
        "@type": "WebSite",
        "@id": siteId,
        url: CANON_ORIGIN + "/",
        name: SITE,
        alternateName: AUTHOR_AKA,
        description: DESCRIPTION,
        inLanguage: "en",
        license: "https://www.apache.org/licenses/LICENSE-2.0",
        author: person,
        creator: person,
        publisher: person,
        image: SIGIL,
        hasPart: [{ "@id": softwareId }, { "@id": DONATE_HREF }, { "@id": softwareId + "-list" }],
      },
      {
        "@type": "SoftwareApplication",
        "@id": runtimeId,
        name: RUNTIME_TITLE,
        applicationCategory: "DeveloperApplication",
        operatingSystem: "Cloudflare Workers",
        softwareVersion: version,
        url: RUNTIME_LOCAL,
        description:
          "Same-origin Aziel Runtime (aziel-runtime) door for agents. OpenAPI " +
          RUNTIME_LOCAL +
          "/openapi.json. MCP POST " +
          RUNTIME_LOCAL +
          "/mcp. Mesh status " +
          RUNTIME_LOCAL +
          "/v1/mesh/status (QNM-BUILD-1.0 suite rollup; live_nodes = presence; GET never enables; suite-presence operator enable). QNS-CD-1.0 photon QNS1 packet transfer cite. Author Aziel Eliab.",
        author: person,
        creator: person,
        isPartOf: { "@id": siteId },
        license: "https://www.apache.org/licenses/LICENSE-2.0",
        codeRepository: GITHUB_RUNTIME,
        sourceCode: {
          "@type": "SoftwareSourceCode",
          name: RUNTIME_TITLE,
          codeRepository: GITHUB_RUNTIME,
          url: GITHUB_RUNTIME,
          author: person,
        },
        sameAs: [GITHUB_RUNTIME, GLAMA_RUNTIME],
        relatedLink: RUNTIME + "/",
        hasPart: namedTools.map((tool) => ({ "@id": tool["@id"] })),
      },
      {
        "@type": "WebAPI",
        "@id": apiId,
        name: RUNTIME_TITLE,
        url: RUNTIME_LOCAL,
        documentation: RUNTIME_LOCAL + "/openapi.json",
        provider: person,
        endpoint: {
          "@type": "EntryPoint",
          url: RUNTIME + "/",
        },
        description:
          "Aziel Runtime (aziel-runtime) door. OpenAPI " +
          RUNTIME_LOCAL +
          "/openapi.json. MCP POST " +
          RUNTIME_LOCAL +
          "/mcp. Mesh " +
          RUNTIME_LOCAL +
          "/v1/mesh/status (QNM-BUILD-1.0 suite rollup; live_nodes = presence; GET never enables). QNS-CD-1.0 cite.",
      },
      {
        "@type": "ItemList",
        "@id": softwareId,
        name: "Software",
        url: SOFTWARE_HREF,
        numberOfItems: doorsSoftware.length,
        itemListElement: doorsSoftware.map((item, i) => ({
          "@type": "ListItem",
          position: i + 1,
          name: item.name,
          url: item.href,
          item: { "@id": softwareNodeId(item) },
        })),
      },
      {
        "@type": "WebPage",
        "@id": DONATE_HREF,
        url: DONATE_HREF,
        name: DONATE_TITLE + " — " + AUTHOR,
        description: DONATE_DESCRIPTION,
        isPartOf: { "@id": siteId },
        author: person,
        about: person,
        inLanguage: "en",
        potentialAction: {
          "@type": "DonateAction",
          name: DONATE_TITLE,
          recipient: person,
          target: DONATE_HREF,
        },
      },
      aboutPageNode(),
      ...sectionPageNodes(),
      {
        "@type": "CollectionPage",
        "@id": softwareId + "-list",
        url: SOFTWARE_HREF,
        name: SOFTWARE_TITLE,
        description: SOFTWARE_DESCRIPTION,
        isPartOf: { "@id": siteId },
        mainEntity: { "@id": softwareId },
        author: person,
        about: person,
        inLanguage: "en",
        relatedLink: [
          SOFTWARE_HREF,
          CANON_ORIGIN + "/v1/software",
          RUNTIME + "/v1/software",
          RUNTIME_LOCAL + "/v1/fraggate/list",
          FRAGGATE,
          TRADES_RUNTIME + "/",
          TRADES_RUNTIME_GITHUB,
        ],
      },
      ...doorsSoftware.map((item) => {
        const node = {
          "@type": "SoftwareApplication",
          "@id": softwareNodeId(item),
          name: item.name,
          url: item.href,
          applicationCategory: "DeveloperApplication",
          author: person,
          isPartOf: { "@id": softwareId },
        };
        const desc = item.description || item.one_line;
        if (desc) node.description = desc;
        return node;
      }),
      ...namedTools,
      faqPageNode(),
      {
        "@type": "SoftwareApplication",
        "@id": TRADES_RUNTIME_ID,
        name: TRADES_RUNTIME_NAME,
        alternateName: TRADES_RUNTIME_SLUG,
        applicationCategory: "DeveloperApplication",
        operatingSystem: "Local TypeScript / Cloudflare Workers giveaway",
        softwareVersion: TRADES_RUNTIME_VERSION,
        url: TRADES_RUNTIME + "/",
        description:
          TRADES_RUNTIME_ONE_LINE +
          " Sister product extra. " +
          AI_CLIENTS_SENTENCE +
          " Author Aziel Eliab.",
        author: person,
        creator: person,
        isPartOf: { "@id": siteId },
        license: "https://www.apache.org/licenses/LICENSE-2.0",
        codeRepository: TRADES_RUNTIME_GITHUB,
        downloadUrl: TRADES_RUNTIME_DOWNLOAD,
        sourceCode: {
          "@type": "SoftwareSourceCode",
          name: TRADES_RUNTIME_NAME,
          codeRepository: TRADES_RUNTIME_GITHUB,
          url: TRADES_RUNTIME_GITHUB,
          author: person,
        },
        sameAs: TRADES_RUNTIME_SAME_AS.slice(),
        relatedLink: [TRADES_RUNTIME_OPENAPI, TRADES_RUNTIME_MCP, TRADES_RUNTIME_CITE, TRADES_RUNTIME_LLMS],
      },
    ],
  };
}
